WITH
	_2TICKET_EVENTS AS (
		SELECT
			EVENT,
			EV.ORGANIZER_SSN
		FROM
			TICKETS TIC
			LEFT JOIN EVENTS EV ON EV.NAME = TIC.EVENT
		GROUP BY
			TIC.EVENT,
			EV.ORGANIZER_SSN
		HAVING
			COUNT(EVENT) >= 2
	)
SELECT
	ORG.SSN
FROM
	ORGANIZERS ORG
	LEFT JOIN _2TICKET_EVENTS _2T ON _2T.ORGANIZER_SSN = ORG.SSN
GROUP BY
	ORG.SSN
HAVING
	COUNT(ORG.SSN) <= 2