SELECT
	O.SSN
FROM
	ORGANIZERS O
	JOIN EVENTS E ON O.SSN = E.ORGANIZER_SSN
	JOIN TICKETS T ON E.NAME = T.EVENT
WHERE
	O.SSN IN (
		SELECT
			ORG.SSN
		FROM
			ORGANIZERS ORG
			JOIN EVENTS EV ON EV.ORGANIZER_SSN = ORG.SSN
		GROUP BY
			ORG.SSN
		HAVING
			COUNT(ORG.SSN) <= 2
	)
GROUP BY
	O.SSN
HAVING
	COUNT(T.TICKET_ID) >= 2